version: "3.8"
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: cryptotrends
      MYSQL_USER: ct_user
      MYSQL_PASSWORD: changeme
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/server
      - /server/node_modules
    depends_on:
      - db
    env_file:
      - ./server/.env
    ports:
      - "4000:4000"

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - server
    environment:
      VITE_API_URL: "http://localhost:4000"
volumes:
  dbdata:
